# Generated by Django 5.0.6 on 2024-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_blockeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
