# Generated by Django 5.0.6 on 2024-10-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_blockeduser_blocked_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
